---
service: snowflake-external-functions

frameworkVersion: '3'

provider:
  name: aws
  # The S3 prefix under which deployed artifacts are stored (default: serverless)
  deploymentPrefix: serverless
  # Configure the S3 bucket used by Serverless Framework to deploy code packages to Lambda
  deploymentBucket:
    # Name of an existing bucket to use (default: created by serverless)
    name: credmark.serverless.${self:provider.region}.${self:provider.stage}.deploys
    # On deployment, serverless prunes artifacts older than this limit (default: 5)
    maxPreviousDeploymentArtifacts: 10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./
        platform: linux/amd64  # Needs to be explicitly defined for building from an ARM based CPU (i.e. Apple Silicon Mac)

functions:
  to_signature:
    image:
      name: appimage
      command: ["handlers.to_signature_handler"]
    events:
      - http:
          path: /api/v1/abi/signature
          method: POST

  to_signature_hash:
    image:
      name: appimage
      command: ["handlers.to_signature_hash_handler"]
    events:
      - http:
          path: /api/v1/abi/signature_hash
          method: POST
