---
service: snowflake-external-functions

frameworkVersion: '3'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./
        platform: linux/amd64  # Needs to be explicitly defined for building from an ARM based CPU (i.e. Apple Silicon Mac)

functions:
  to_signature:
    image:
      name: appimage
      command: ["handlers.to_signature_handler"]
    events:
      - http:
          path: /api/v1/abi/signature
          method: POST

  to_signature_hash:
    image:
      name: appimage
      command: ["handlers.to_signature_hash_handler"]
    events:
      - http:
          path: /api/v1/abi/signature_hash
          method: POST
